version: "3"

services:
  postgis:
    image: kartoza/postgis:12.0
    ports:
      - 5434:5432
    environment:
      - DEFAULT_ENCODING="UTF-8"
#      - DEFAULT_COLLATION="de_AT.utf8"
#      - DEFAULT_CTYPE="de_AT.utf8"
      - --auth="md5"
#      - INITDB_EXTRA_ARGS=""
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DBNAME=postgres
      - ALLOW_IP_RANGE="0.0.0.0/0"
#      - IP_LIST=<*>
      - EXTRA_CONF=shared_buffers = 500MB \n work_mem = 16MB \n maintenance_work_mem = 128MB \n wal_buffers = 1MB \n random_page_cost = 2
    volumes:
      - ./postgis_data:/var/lib/postgresql
  geoserver:
    image: kartoza/geoserver:2.17.0
    ports:
      - 8088:8080
    volumes:
      - ./geoserver_data:/opt/geoserver/data_dir
      - ./../webapp:/opt/geoserver/data_dir/www